version: "3.9"

services:
  db:
    image: postgres:16
    container_name: c2s_db
    environment:
      POSTGRES_DB: c2s
      POSTGRES_USER: c2suser
      POSTGRES_PASSWORD: c2spass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U c2suser -d c2s"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: c2s_web
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  pgdata:
