# Generated by Django 4.2.16 on 2025-10-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=80, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('engine', models.CharField(max_length=40, verbose_name='Motorização')),
                ('fuel_type', models.CharField(max_length=30, verbose_name='Combustível')),
                ('color', models.CharField(max_length=30, verbose_name='Cor')),
                ('mileage_km', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('doors', models.PositiveSmallIntegerField(default=4, verbose_name='Portas')),
                ('transmission', models.CharField(max_length=20, verbose_name='Transmissão')),
                ('body_type', models.CharField(max_length=30, verbose_name='Carroceria')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
                ('vin', models.CharField(max_length=32, unique=True, verbose_name='VIN/Chassi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
