# Generated by Django 4.2.16 on 2025-10-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vin',
        ),
    ]
