# Generated by Django 4.2.16 on 2025-10-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default=1, max_length=32, unique=True, verbose_name='VIN/Chassi'),
            preserve_default=False,
        ),
    ]
